import type { Metadata } from "next";
import { Abel, Alexandria } from "next/font/google";
import "./globals.css";

const fontSans = Alexandria({
  variable: "--font-alexandria",
  subsets: ["latin"],
});

const fontMono = Abel({
  variable: "--font-abel",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} ${fontMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
